// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type LinktreeDocumentDataSlicesSlice =
  | SocialLinksSlice
  | LinkButtonsSlice
  | ProfileSectionSlice;

/**
 * Content for Linktree documents
 */
interface LinktreeDocumentData {
  /**
   * Slice Zone field in *Linktree*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LinktreeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Linktree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: linktree.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Linktree*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: linktree.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Linktree*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Linktree document from Prismic
 *
 * - **API ID**: `linktree`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinktreeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LinktreeDocumentData>,
    "linktree",
    Lang
  >;

export type AllDocumentTypes = LinktreeDocument;

/**
 * Item in *LinkButtons → Default → Primary → linkbuttons*
 */
export interface LinkButtonsSliceDefaultPrimaryLinkbuttonsItem {
  /**
   * url field in *LinkButtons → Default → Primary → linkbuttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: url of link button
   * - **API ID Path**: link_buttons.default.primary.linkbuttons[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * button text field in *LinkButtons → Default → Primary → linkbuttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: text of button
   * - **API ID Path**: link_buttons.default.primary.linkbuttons[].button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Primary content in *LinkButtons → Default → Primary*
 */
export interface LinkButtonsSliceDefaultPrimary {
  /**
   * linkbuttons field in *LinkButtons → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_buttons.default.primary.linkbuttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  linkbuttons: prismic.GroupField<
    Simplify<LinkButtonsSliceDefaultPrimaryLinkbuttonsItem>
  >;
}

/**
 * Default variation for LinkButtons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinkButtonsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkButtonsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkButtons*
 */
type LinkButtonsSliceVariation = LinkButtonsSliceDefault;

/**
 * LinkButtons Shared Slice
 *
 * - **API ID**: `link_buttons`
 * - **Description**: LinkButtons
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LinkButtonsSlice = prismic.SharedSlice<
  "link_buttons",
  LinkButtonsSliceVariation
>;

/**
 * Primary content in *ProfileSection → Default → Primary*
 */
export interface ProfileSectionSliceDefaultPrimary {
  /**
   * Avatar image field in *ProfileSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profile_section.default.primary.avatar_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar_image: prismic.ImageField<never>;

  /**
   * username field in *ProfileSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: username (it shows @username)
   * - **API ID Path**: profile_section.default.primary.username
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  username: prismic.KeyTextField;
}

/**
 * Default variation for ProfileSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProfileSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProfileSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProfileSection*
 */
type ProfileSectionSliceVariation = ProfileSectionSliceDefault;

/**
 * ProfileSection Shared Slice
 *
 * - **API ID**: `profile_section`
 * - **Description**: ProfileSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProfileSectionSlice = prismic.SharedSlice<
  "profile_section",
  ProfileSectionSliceVariation
>;

/**
 * Item in *SocialLinks → Default → Primary → social link*
 */
export interface SocialLinksSliceDefaultPrimarySocialLinkItem {
  /**
   * platform field in *SocialLinks → Default → Primary → social link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: social platform
   * - **API ID Path**: social_links.default.primary.social_link[].platform
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform: prismic.KeyTextField;

  /**
   * social url field in *SocialLinks → Default → Primary → social link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: link social media
   * - **API ID Path**: social_links.default.primary.social_link[].social_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SocialLinks → Default → Primary*
 */
export interface SocialLinksSliceDefaultPrimary {
  /**
   * social link field in *SocialLinks → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_links.default.primary.social_link[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_link: prismic.GroupField<
    Simplify<SocialLinksSliceDefaultPrimarySocialLinkItem>
  >;
}

/**
 * Default variation for SocialLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialLinksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialLinks*
 */
type SocialLinksSliceVariation = SocialLinksSliceDefault;

/**
 * SocialLinks Shared Slice
 *
 * - **API ID**: `social_links`
 * - **Description**: SocialLinks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialLinksSlice = prismic.SharedSlice<
  "social_links",
  SocialLinksSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LinktreeDocument,
      LinktreeDocumentData,
      LinktreeDocumentDataSlicesSlice,
      AllDocumentTypes,
      LinkButtonsSlice,
      LinkButtonsSliceDefaultPrimaryLinkbuttonsItem,
      LinkButtonsSliceDefaultPrimary,
      LinkButtonsSliceVariation,
      LinkButtonsSliceDefault,
      ProfileSectionSlice,
      ProfileSectionSliceDefaultPrimary,
      ProfileSectionSliceVariation,
      ProfileSectionSliceDefault,
      SocialLinksSlice,
      SocialLinksSliceDefaultPrimarySocialLinkItem,
      SocialLinksSliceDefaultPrimary,
      SocialLinksSliceVariation,
      SocialLinksSliceDefault,
    };
  }
}
