// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  link_buttons: dynamic(() => import("./LinkButtons")),
  profile_section: dynamic(() => import("./ProfileSection")),
  social_links: dynamic(() => import("./SocialLinks")),
};
